### ISSUE TITLE
When I try to run this program I get the following errors...

### ISSUE THREAD

**Issue by Ryan-Lima** [catchin/TimeLapsing#1]
I attempted to make a batch of images into a timelapse using tl.py. 

I have about 10,000 images, they are all .jpg 

Your input image has dimensions 3888x2592.

Enter the conversion you want to do.
Examples:
 -crop 3888x2187+0+202 +repage -scale 1920x1080
 -crop 3888x2187+0+202 +repage -scale 1920x1080 -level 3,95
 -rotate 2.0 -crop 2087x1174+42+84 +repage -scale 1920x1080

Enter a blank line when you are satisfied with the output image.

=> 
Converting 12238 imagesTraceback (most recent call last):
  File "tl.py", line 177, in <module>
    tl.run()
  File "tl.py", line 154, in run
    self.convertAll()
  File "tl.py", line 62, in convertAll
    self.convertSingle(f, destFile)
  File "tl.py", line 69, in convertSingle
    args.extend(self.options)
TypeError: 'NoneType' object is not iterable

Any ideas what is causing this error?

**Comment by catchin** [comment]
Hi @Ryan-Lima, the program currently expects that you enter one of the conversions. Can you try to enter, e.g., `-crop 3888x2187+0+202 +repage -scale 1920x1080` into the prompt? Then it should display the cropped and scaled image. After that you can enter a blank line.
